Models/Payment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace B2BDotCom.Models
{
    public class Payment
    {
        public string email { get; set; }
        public double amount { get; set; }
        public string invoiceNbr { get; set; }
    }
}

Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace B2BDotCom.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            ViewBag.Title = "About Us";
            return View();
        }

        public ActionResult History()
        {
            ViewBag.Title = "History";
            return View();
        }

        public ActionResult Management()
        {
            ViewBag.Title = "Management";
            return View();
        }

        public ActionResult Testimonials()
        {
            ViewBag.Title = "Testimonials";
            return View();
        }

        public ActionResult Compliance()
        {
            ViewBag.Title = "Compliance Information Security";
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using B2BDotCom.Models;
using Stripe;
using Stripe.Checkout;

namespace B2BDotCom.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home";
            return View();
        }

        public ActionResult Faq()
        {
            ViewBag.Title = "Frequently Asked Questions";
            return View();
        }

        public ActionResult Sitemap()
        {
            ViewBag.Title = "Site Map";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Title = "Contact Us";
            return View();
        }

        public ActionResult SubmitPayment()
        {
            ViewBag.Title = "Submit Payment";
            return View();
        }
        public ActionResult PaymentSuccess()
        {
            ViewBag.Title = "Payment Success";
            return View();
        }
        public ActionResult PaymentError()
        {
            ViewBag.Title = "Payment Error";
            return View();
        }

        /// <summary>
        /// Create Payment intents.  This will be invoked via a javascript fetch object.  Will need to pass some data to this (amount, etc)
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Secret()
        {
            var resolveRequest = HttpContext.Request;
            Payment pmt = null;
            resolveRequest.InputStream.Seek(0, SeekOrigin.Begin);
            string jsonString = new StreamReader(resolveRequest.InputStream).ReadToEnd();
            if (jsonString != null)
            {
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                pmt = (Payment) serializer.Deserialize(jsonString, typeof(Payment));
            }

            var ll = Convert.ToInt64(compute_cents(pmt.amount));


            var uniqueId = (DateTime.Now.Ticks - new DateTime(2016, 1, 1).Ticks).ToString("x").ToUpper();
            var options = new PaymentIntentCreateOptions
            {
                Amount = ll,
                Currency = "usd",
                Description = "Invoice #" + pmt.invoiceNbr,
                ReceiptEmail = pmt.email,
                // Verify your integration in this guide by including this parameter
                Metadata = new Dictionary<string, string>
                {
                    { "integration_check", "accept_a_payment" },
                    { "receipt_email", pmt.email },
                    { "invoice_number", pmt.invoiceNbr },
                    { "transaction_number", uniqueId },
                },
            };

            var service = new PaymentIntentService();
            var paymentIntent = service.Create(options);
            return Json(paymentIntent, JsonRequestBehavior.AllowGet);
        }

        static int compute_cents(double dollar_amount)
        {
            return (int)(dollar_amount * 100);
        }
    }
}

Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace B2BDotCom.Controllers
{
    public class ProcessController : Controller
    {
        // GET: Process
        public ActionResult Index()
        {
            ViewBag.Title = "Process in a Nutshell";
            return View();
        }

        public ActionResult HowToPrepare()
        {
            ViewBag.Title = "How the Broker Prepares";
            return View();
        }

        public ActionResult HowBranchPrepares()
        {
            ViewBag.Title = "How the Branch Prepares";
            return View();
        }
    }
}

Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace B2BDotCom.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Index()
        {
            ViewBag.Title = "Basic Projects";
            return View();
        }

        public ActionResult Overview()
        {
            ViewBag.Title = "Overview";
            return View();
        }

        public ActionResult AnnouncementServices()
        {
            ViewBag.Title = "Announcement Services";
            return View();
        }

        public ActionResult SpecialProjects()
        {
            ViewBag.Title = "Special Projects";
            return View();
        }

        public ActionResult Pricing()
        {
            ViewBag.Title = "Pricing";
            return View();
        }
    }
}

Controllers/TurnAroundController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace B2BDotCom.Controllers
{
    public class TurnAroundController : Controller
    {
        // GET: TurnAround
        public ActionResult Index()
        {
            ViewBag.Title = "Basic Projects";
            return View();
        }

        public ActionResult RapidTurnaround()
        {
            ViewBag.Title = "Rapid Turnaround";
            return View();
        }
    }
}

Views/About/Compliance.cshtml
@model dynamic

@section navigation {
    @Html.Partial("_AboutUsMenu")
}

    <p>When you use Broker to Broker, you can rest assured that maintaining compliance and your critical data’s security is crucial to us. </p>
    <p>In today’s litigious world, it’s imperative that you maintain vigilance with regard to your compliance and data security processes, not only internally, but externally through your partners and vendors as well.</p>
    <p>At Broker to Broker, we are a compliance-driven organization. Given that we service the Financial Services Industry, regulatory requirements and data security are constantly at the forefront of our process discussions and improvements. We continually strive to maintain very high levels of security in everything we do.</p>
    <p>Our primary responsibility is to handle your mailings as you wish. We can and will be very flexible in that regard. However, there are many pitfalls in the ACAT mailing process, and it is heavily regulated through compliance organizations and industry agreements. With over 17 years of experience, we can help you navigate those pitfalls and help keep you in compliance to reduce your chances of jeopardizing your clients or your business.</p>
    <p>Although we very rarely receive truly sensitive data from our clients, we treat every piece of information we receive with utmost security.&nbsp; Equally important is our promise not to expose or release any client information in providing our services except as instructed by you.</p>

Views/About/History.cshtml
@model dynamic

@section navigation {
    @Html.Partial("_AboutUsMenu")
}
<p>As the first pioneers of the outsourced broker transfer mailing industry, Broker to Broker began as a home-based business in May of 1991 in Columbus, Ohio with a rented PC and a dot matrix printer that promised to produce an impressive two pages per minute. </p>
<p> It quickly grew from one location to three – Columbus, Pittsburgh and Nashville – and moved out of the realm of home-based enterprise.&nbsp; As the business steadily grew to become the industry standard, so did the need for more sophisticated technology and operational consistency. In 1999, all processing was moved to Nashville. Shortly after the consolidation and relocation, the staff of roughly 30 moved into a brand new, state of the art, 15,000 square foot facility where the company resides to this day.</p>
<p> For over 17 years now, Broker to Broker has worked with thousands of branch offices on over ten thousand broker transfer mailings covering several million clients.</p>
<p> Over the last few years, significant changes have occurred in the industry. These changes have created some unique and difficult issues to overcome in the broker transfer mailing process. Today, Broker to Broker continues to create revolutionary service improvements to provide solutions for these issues. Working closely with our partners and clients, Broker to Broker is implementing automation, hardware, software and innovative process changes to create solutions for the quality, precision, and timeliness the industry demands. We are continuously adding capacity to better fit the resources required as we forge new ground in this ever-changing industry. No project is too large for Broker to Broker. From 500 to 500,000 accounts or more, we stand ready to put our expertise to work for YOU.</p>

Views/About/Index.cshtml
@model dynamic

@section navigation {
    @Html.Partial("_AboutUsMenu")
}

<p>
    <strong class="style3mini">
        We make the transition of a new broker into your firm a whole lot easier.
    </strong>
</p>

<p>Using <strong>Broker to Broker</strong> is simple. We are like an instant off-site staff to handle this often burdensome process.</p>
<p><strong>Broker to Broker</strong> prepares Automated Customer Account Transfer (ACAT) forms and other necessary documents for clients on behalf of advisors who are moving to a new firm. Mailings can be sent directly to the clients or to the coordinating office for distribution.</p>
<p>We do the work for you. We tackle the critical task of preparing mailings that the broker sends to their clients announcing their move to your firm.</p>
<p>Broker to Broker eases the concerns brokers and their clients have about the transition process. We provide a professional first impression of your firm to your new broker’s clients, thereby enhancing recruiting and client retention success.</p>
<p>
    <strong>What are the benefits of using a service such as ours?</strong>
</p>
<p>
    <strong>Convenience</strong><br>
    Your schedule is already full. Sit back and let us do the work of preparing your mailings. We have an experienced staff and a very well defined process you can leverage to minimize the time and resource commitments required of you and your team.<strong></strong>
</p>
<p>
    <strong>Quality</strong><br>
    You have access to our expertise with over 17 years designing, improving, and perfecting the client transfer process. We’ve helped thousands of branches and millions of clients transfer smoothly to their new firm. Let us help you as well.
</p>
<p>
    <strong>Accuracy</strong> <br>
    We’ve learned quite a few important things over the years. All our industry experience is at your fingertips as we work with you every step of the way to ensure your client data, documents, and packets are exactly the way you want them to be, and your client needs them to be.
</p>
<p>
    <strong>Professional Appearance</strong><br>
    You only get one chance to make a good first impression. Make a great first impression with Broker to Broker’s personalized, professional mailing packets.
</p>
<p>
    <strong>Rapid Turnaround</strong><br>
    When you have a new broker coming on board, you need to get your client paperwork out as quickly as possible. We can get your packets out rapidly to ensure a smooth transition of your broker’s clients.
</p>
<p>
    <strong>
        Discrete, Off-Site Preparation<br>
    </strong>Minimize the disruption of your regular office routine along with rumors and overtime for your staff. We handle everything at our own production facility and coordinate discretely with your internal transition team.
</p>
<p>
    <strong>Price</strong><br>
    You can reap the benefits of our economies of scale and have your transitions professionally handled at a cost that’s most often less than doing them in house or using temporary personnel who have little or no experience. The bottom line: We save you time AND money!
</p>
<p>
    <strong>Confidentiality</strong><br>
    Confidentiality is absolutely assured! We understand your need to keep your client information confidential, and we take it very seriously. All client information is diligently protected and will not be sold or used for any other reason. When the project is completed, all information is returned to you and removed from our systems.
</p>
<p class="style3mini">Our Philosophies</p>
<ul>
    <li>Every employee in the company works for one department – Client Support</li>
    <li>We grow by achieving Outstanding Results for our Clients</li>
    <li>Quality Service is first and foremost in everything we do</li>
    <li>We hire the best... so we Expect the Best</li>
    <li>We are Committed to the Highest Ethical Standards</li>
    <li>Personal Honesty and Integrity are Fundamental to our Success</li>
    <li>Teamwork is Everything</li>
    <li>Adherence to Data Security and Compliance Requirements is a Core Competency</li>
    <li>We Drive our Industry through Constant Innovation</li>
</ul>

Views/About/Testimonials.cshtml
@model dynamic


@section navigation {
    @Html.Partial("_AboutUsMenu")
}


        <blockquote>
            “Using Broker to Broker is the best thing I’ve done. Complete confidentiality, no overtime for my staff, no rumors, no unsettling of the office.” <br>
            <strong>Branch Manager</strong>
        </blockquote>

        <blockquote>
            
                “I just give the necessary information to Broker to Broker and sit back while all the work is performed by experts who know their business… Hassle-free, professionally handled, tailored to meet my broker’s needs.” <br>
                <strong>Operations Manager</strong>
            
        </blockquote>
        <blockquote>
            
                “Client [mailings] have been handled professionally and discreetly. My region plans to continue using Broker to Broker and recommends them highly to anyone in the securities business. <br>
                <strong>Regional Director</strong>
            
        </blockquote>
        <blockquote>
            
                “Your professional, quality product has impressed every broker we have brought to our firm and reinforced in our brokers’ and clients’ minds that they made the right decision. Broker to Broker has become an integral part of our business.” <br>
                <strong>Regional Ops Manager</strong>
            
        </blockquote>
        <blockquote>
        
            "I was totally blown away by the professionalism, quality and service that Broker to Broker has provided to us. &nbsp;We are a top three brokerage firm, and this level of service is unheard of! The attention to every last detail is astounding... We will use Broker to Broker at every occasion as they are able to process our outgoing ACAT packages better than I can in house!"<br>
            <strong>Operations Manager - AVP</strong>
        
        </blockquote>

Views/Home/Sitemap.cshtml
@model dynamic

@section navigation
{

    <br />
    <p align="center"><a href="@Url.Action("Contact", "Home")"><img src="../../Images/contactnow.gif" width="210" height="62" border="0"></a></p>

}

<a href="@Url.Action("Index", "Home")">Home</a>
<p><a href="@Url.Action("Index", "Services")">Services</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Index", "Services")">Basic Projects </a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("AnnouncementServices", "Services")">Announcement Services</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("SpecialProjects", "Services")">Special Projects</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Pricing", "Services")">Pricing</a>  </p>
<p><a href="@Url.Action("Index", "TurnAround")">Turn Around</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Index", "TurnAround")">Basic Projects</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("RapidTurnaround", "TurnAround")">Rapid Turnaround - Protocol Compliant Projects </a></p>
<p><a href="@Url.Action("Index", "Process")">Process</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Index", "Process")">Process in a Nutshell</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("HowToPrepare", "Process")">How the Broker Prepares</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("HowBranchPrepares", "Process")">How the Branch Prepares</a>   </p>
<p><a href="@Url.Action("Index", "About")">About Us</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("History", "About")">Company History</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Management", "About")">Management</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Testimonials", "About")">Testimonials</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Compliance", "About")">Compliance / Information Security  </a></p>
<p><a href="@Url.Action("Faq", "Home")">Frequently Asked Questions</a></p>
<p><a href="@Url.Action("Contact", "Home")">Contact Us  </a></p>

Views/Process/HowBranchPrepares.cshtml
@model dynamic


@section navigation {
    @Html.Partial("_ProcessMenu")
}


<p>
    The success and ease of a project lie in good planning and coordination. The best way to ensure your project goes smoothly is to provide us with complete and accurate information, and get materials shipped to us as scheduled. <br>
</p>

<ol class="processList">
    <li>
        Contact Broker To Broker to schedule a project.<br />
        <table cellspacing="0" cellpadding="4" border="0">
            <tbody>
                <tr>
                    <td width="30" valign="top" align="center">&nbsp;</td>
                    <td colspan="2" valign="top" align="left">
                        Provide the following information:<br>
                        <table cellspacing="0" cellpadding="4" border="0">
                            <tbody>
                                <tr>
                                    <td width="30" valign="top" align="center">&nbsp;</td>
                                    <td colspan="2">the exact number of accounts (brokerage accounts, plus outside mutual funds and outside annuities)</td>
                                </tr>
                                <tr>
                                    <td width="30" valign="top" align="center">&nbsp;</td>
                                    <td colspan="2">the date you will get the project materials to Broker To Broker</td>
                                </tr>
                                <tr>
                                    <td width="30" valign="top" align="center">&nbsp;</td>
                                    <td colspan="2">the date you need the project mailed to your clients or back in your office</td>
                                </tr>
                                <tr>
                                    <td width="30" valign="top" height="45" align="center">&nbsp;</td>
                                    <td colspan="2" height="45" align="left">the type of service you wish to employ (Basic, Basic Plus, etc.)</td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr valign="top">
                    <td width="30" valign="top" align="center">&nbsp;</td>
                    <td colspan="2" valign="top" align="left">We will send to you a Project Contract. This form also serves as a blueprint for how you want us to handle your project.</td>
                </tr>
            </tbody>
        </table>
    </li>
    <li>
        Ensure the Broker’s Client Information has been prepared <br>
        (see <a href="@Url.Action("HowToPrepare", "Process")" target="_top">How the Broker Prepares for a Project</a>).<br>
        <table cellspacing="0" cellpadding="4" border="0">
            <tbody>
            <tr valign="top">
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">In addition to brokerage account information, be sure information for "outside" Mutual Funds and Annuities has been included, if applicable.</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Check to see if the broker wants customized letter salutations (e.g., "Dear Jim and Peggy") and has noted them directly on the records given to us. Unless otherwise noted, "Mr. and Mrs.", "Dr.", etc. are used.</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Make sure the records have been alphabetized to facilitate "householding" of clients. </td>
            </tr>
            </tbody>
        </table>
    </li>
    <li>
        Prepare a prototype Cover Letter for the mailings.<br>
        <table cellspacing="0" cellpadding="4" border="0">
            <tbody>
            <tr valign="top">
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Decide on an appropriate date for the letter, or you may choose to leave the letter undated for flexibility.</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">If the letter has not been pre-approved internally, please do so before forwarding it to us to avoid delays during the project.</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">
                    If applicable, see that the sender of the letter (Broker or Branch Manager) has provided a signature sample for scanning into the cover letter. <br>
                </td>
            </tr>
            </tbody>
        </table>
    </li>
    <li>Complete all areas of the Project Contract and return it to us. Work cannot begin on your project until this form is fully completed and received.</li>
    <li>
        Gather the required project materials for shipping to Broker to Broker. Refer to the Project Contract for a specific materials list.
        <table cellspacing="0" cellpadding="4" border="0">
            <tbody>
            <tr valign="top">
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Client information</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Mailing Supplies (letterhead, envelopes, etc.)</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Cover Letter and Signature Samples (if signature scan is desired)</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Forms (ACATs plus other forms that you wish to include for client accounts). This step may not be necessary for clients who utilize electronic ("PDF") forms.</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Business cards for the broker, if available.</td>
            </tr>
            <tr>
                <td width="30" valign="top" align="center">&nbsp;</td>
                <td colspan="2" valign="top" align="left">Promotional inserts you wish to include</td>
            </tr>
            </tbody>
        </table>
    </li>
    <li>Ship the project materials to Broker To Broker via your regular overnight carrier. Please be sure to package the materials securely to avoid damage in transit.</li>

</ol>

<p>
    <strong>
        <em>Please call us if your project or shipping plans change, so that we can "reschedule" the project appropriately.</em>
    </strong>
</p>

Views/Services/Pricing.cshtml
@model dynamic

@section navigation {
    @Html.Partial("_ServicesMenu")
}


        <p>
        Broker to Broker utilizes a unit pricing schedule. Pricing is based on the number of accounts, the number of documents produced, and the specialized processing you request. Most of our clients find we can produce their mailings for less cost than they can produce them internally. We’re confident we can save you time and money as well.
        </p>
        <p>
            For "Basic" Projects, there is a standard price for each account processed. When utilizing our "Basic Plus" service, an additional cost is attached to each supplemental form we produce.
        </p>
        <p>
            There is a $200 project minimum.
        </p>
        <p>
            <strong class="style3mini">Additional Expenses</strong><br>
            It is sometimes necessary for us to charge additional costs for non-standard processing, especially manually intensive tasks. These additional costs are generally very minimal and may be controlled with proper planning and preparation. The most frequently incurred additional expenses are associated with
            <ul>
                <li>Folders</li>
                <li>Affixing "Sign Here" stickers</li>
                <li>Creating mailing and return envelopes</li>
                <li>Mailing inserts (brochures and promotional materials)</li>
                <li>Rapid Turn Around Projects </li>
            </ul>
        <p>
            <strong class="style3mini">Controlling Costs</strong><br>
            There are ways to control some of the costs associated with projects coordinated through Broker to Broker. This control lies mostly in good planning.
        </p>
        <ul>
            <li>Always allow us sufficient time to complete a project. We require a minimum lead-time of five business days to handle any project (ten business days is preferred for non-rush projects). A Rush Fee is charged whenever an insufficient number of days is allowed or when a return date is accelerated.</li>
            <li>Always provide us with a reasonably accurate estimate of the project size (i.e., the number of accounts to be processed). When identifying the total number of accounts, add all brokerage accounts, outside mutual fund accounts and outside annuity accounts. </li>
            <li>Provide the entire project to us at the same time. Accounts that are added after the original project is received may need to be handled as separate projects, subject to our project minimum.</li>
            <li>Prepare and arrange client records so they are user-ready (see "<a href="@Url.Action("HowToPrepare", "Process")">How The Broker Prepares for a Project</a>"). We prefer to receive information in alphabetical order for ease in householding. A fee may be charged for this service. There are also additional charges if we must cross-reference multiple groupings or lists of client records.</li>
        </ul>
        <p><strong><em>Please contact us for more detailed pricing information and other ways you may control your costs.</em></strong></p>

Views/Shared/_HMenu.cshtml
<nav class="navbar container navbar-expand-sm navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar1">
            <ul class="navbar-nav nav nav-fill w-100">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">SERVICES</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="@Url.Action("Index", "Services")">Overview</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Index", "Services")">Basic Projects </a></li>
                        <li><a class="dropdown-item" href="@Url.Action("AnnouncementServices", "Services")">Announcements</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("SpecialProjects", "Services")">Special Projects</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Pricing", "Services")">Pricing</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">TURN AROUND</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="@Url.Action("Index", "TurnAround")"> Basic Projects</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("RapidTurnaround", "TurnAround")"> Rapid Turnaround </a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">PROCESS</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="@Url.Action("Index", "Process")"> Process in a Nutshell</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("HowToPrepare", "Process")"> How the Broker Prepares </a></li>
                        <li><a class="dropdown-item" href="@Url.Action("HowBranchPrepares", "Process")"> How the Branch Prepares</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">ABOUT US</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="@Url.Action("Index", "About")"> About Us</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("History", "About")"> Company History </a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Management", "About")"> Management</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Testimonials", "About")"> Testimonials</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Compliance", "About")"> Compliance/Information Security</a></li>
                    </ul>
                </li>

                <a class="nav-item nav-link" href="@Url.Action("SubmitPayment", "Home")">PAYMENT</a>
                    

            </ul>
        </div>
    </div>
</nav>